version: "3"
services:
  keycloak:
    image: jboss/keycloak
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=123456789
    restart: always
    volumes:
      - .keycloak/:/opt/keycloak/data/h2/
  mysql_db:
    restart: always
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - "MYSQL_DATABASE=core_bank"
      - "MYSQL_USER=hieudx1"
      - "MYSQL_PASSWORD=123456789"
      - "MYSQL_ROOT_PASSWORD=123456789"
    ports:
      - "3309:3306"
    networks:
      - microservice_internal
  registry:
    container_name: registry
    build:
      context: registry
      dockerfile: Dockerfile
    image: registry:latest
    depends_on:
      - mysql_db
    ports:
      - 8761:8761
    networks:
      - microservice_internal
  gateway:
    container_name: gateway2
    build:
      context: gateway2
      dockerfile: Dockerfile
    image: gateway2:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://registry:8761/eureka/
    depends_on:
      - registry
      - keycloak
    ports:
      - 8081:8081
    networks:
      - microservice_internal
  user_service:
    container_name: user_service
    build:
      context: usersevice
      dockerfile: Dockerfile
    image: user_service:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://registry:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql_db:3306/core_bank
    depends_on:
      - registry
      - mysql_db
      - keycloak
    ports:
      - 8082:8081
    networks:
      - microservice_internal
  payment:
    container_name: payment
    build:
      context: payment
      dockerfile: Dockerfile
    image: payment:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://registry:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql_db:3306/core_bank
    depends_on:
      - registry
      - mysql_db
      - keycloak
    ports:
      - 8083:8081
    networks:
      - microservice_internal
  fund_transfer:
    container_name: fund_transfer
    build:
      context: fund_transfer
      dockerfile: Dockerfile
    image: fund_transfer:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://registry:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql_db:3306/core_bank
    depends_on:
      - registry
      - mysql_db
      - keycloak
    ports:
      - 8084:8081
    networks:
      - microservice_internal
  core_bank:
    container_name: core_bank
    build:
      context: core_bank
      dockerfile: Dockerfile
    image: core_bank:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://registry:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql_db:3306/core_bank
    depends_on:
      - registry
      - mysql_db
      - keycloak
    ports:
      - 8085:8081
    networks:
      - microservice_internal
  centralize_config:
    container_name: centralize_config
    build:
      context: centralize_config
      dockerfile: Dockerfile
    image: centralize_config:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://registry:8761/eureka/
    depends_on:
      - registry
      - mysql_db
      - keycloak
    ports:
      - 8086:8081
    networks:
      - microservice_internal
    
networks:
  microservice_internal:
    driver: bridge


volumes:
  db:
    driver: local
