spring:
  application:
    name: core-banking-service
  datasource:
    url: jdbc:mysql://localhost:3309/core_bank
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: ${spring.application.name}