server:
  port: 8963

app:
  config:
    keycloak:
      url: http://localhost:8080/auth
      realm: hieudx-internet-banking
      client-secret: q5k8vmoefw4GRj4trZ5Y3EZTUHocfegq
      client-id: internet-banking-core-client



spring:
  main:
    web-application-type: reactive
  application:
    name: internet-banking-api-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            user-info-authentication-method: header
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          internet-banking-core-client:
            authorization-grant-type: authorization_code
            client-id: ${app.config.keycloak.client-id}
            client-secret: ${app.config.keycloak.client-secret}
            provider: keycloak
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: internet-banking-user-service
          uri: lb://internet-banking-user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: internet-banking-fund-transfer-service
          uri: lb://internet-banking-fund-transfer-service
          predicates:
            - Path=/fund-transfer/**
          filters:
            - StripPrefix=1
        - id: core-banking-service
          uri: lb://core-banking-service
          predicates:
            - Path=/banking-core/**
          filters:
            - StripPrefix=1
        - id: internet-banking-utility-payment-service
          uri: lb://internet-banking-utility-payment-service
          predicates:
            - Path=/utility-payment/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO